branch-defaults:
  colombia:
    environment: api-elecciones-co-2022
    group_suffix: null
global:
  application_name: api-elecciones-co-2022
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
